### ISSUE TITLE
Installing the nodejs package

### ISSUE THREAD

**Issue by brocc0li** [thelinmichael/spotify-web-api-node#88] opened 2016-10-16 18:39 UTC
Node.js Command prompt output

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "spotify-web-api-node" "--save"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 6:1
npm ERR! }
npm ERR! ^
npm ERR! File: C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\npm-debug.log

C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch>npm install spotify-web-api-node
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "spotify-web-api-node"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 6:1
npm ERR! }
npm ERR! ^
npm ERR! File: C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\npm-debug.log

npn-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'spotify-web-api-node' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
5 verbose stack Error: Failed to parse json
5 verbose stack Trailing comma in object at 6:1
5 verbose stack }
5 verbose stack ^
5 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)

5 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
6 verbose cwd C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch
7 error Windows_NT 10.0.14393
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "spotify-web-api-node"
9 error node v4.4.7
10 error npm  v2.15.8
11 error file C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
12 error code EJSONPARSE
13 error Failed to parse json
13 error Trailing comma in object at 6:1
13 error }
13 error ^
14 error File: C:\Users\Broccoli-GO\Desktop\scripts\bots\twitch\package.json
15 error Failed to parse package.json data.
15 error package.json must be actual JSON, not just JavaScript.
15 error
15 error This is not a bug in npm.
15 error Tell the package author to fix their package.json file. JSON.parse
16 verbose exit [ 1, true ]

**Comment by JMPerez** [comment] 2016-10-16 20:02
There seems to be a syntax issue in your package.json. Thus, it doesn't seem to be related with the spotify-web-api-node package.

I'm closing this issue. Feel free to reopen it if you still think it is caused by this package.

**Closed by JMPerez** 2016-10-16 20:02 UTC
