### ISSUE TITLE
Playback control

### ISSUE THREAD

**Issue by dreszczyk** [thelinmichael/spotify-web-api-node#118] opened 2017-04-15 17:10 UTC
Due to lastest _beta_ changes we can [control playback](https://github.com/spotify/web-api/issues/15#issuecomment-290762329) from API. Is this package capable of doing this?

**Comment by JMPerez** [comment] 2017-04-16 09:31
Closing as duplicate of https://github.com/thelinmichael/spotify-web-api-node/issues/114

**Closed by JMPerez** 2017-04-16 09:31 UTC
