### ISSUE TITLE
Error node modules

### ISSUE THREAD

**Issue by kaysan13** [thelinmichael/spotify-web-api-node#231] opened 2018-07-30 22:04 UTC
Hello
First of all thanks for your work on spotify-web-api-node.
I'm coming to you because I have a problem with this module.

I install the package via the npm -S i spotify-web-api-node command.
Once installed the package appears well in the nodes_modules.

When importing the module I have an error:

var SpotifyWebApi = require(spotify-web-api-js)
ReferenceError: spotify is not defined

Do you have any idea where this problem might have come from? Because as
much as I tried to install

     "spotify":"^0.3.0",
     "spotify-api": "0.0.0",
     "spotify-web-api-node":"^3.1.1"

I don't see a solution.

Thank you

**Comment by zmilonas** [comment] 2018-08-11 23:56
That is not this package's problem. 

You added `spotify` and `spotify-api` as dependencies and seems like these do not exist

**Comment by JMPerez** [comment] 2018-09-13 08:46
Closing the ticket since the issue is not related with this library.

**Closed by JMPerez** 2018-09-13 08:46 UTC
