### ISSUE TITLE
createPlaylists endpoint no longer working

### ISSUE THREAD

**Issue by jmfortunatojr** [thelinmichael/spotify-web-api-node#139] opened 2017-06-12 16:28 UTC
Hello - 

We've been using your library successfully for the past several months, but noticed today that the createPlaylists endpoint no longer works. It always returns a 400 Bad Request.

**Comment by jpiepkow** [comment] 2017-06-12 16:31
yep its not just this library either. I have opened up a issue in the main web-api repo because testing in the spotify console returns 400 also

**Comment by jpiepkow** [comment] 2017-06-12 16:31
https://github.com/spotify/web-api/issues/573

If you could comment there it would be super helpful!

**Comment by JMPerez** [comment] 2017-08-31 22:17
Closing this ticket since the issue is not related with the code of the wrapper.

**Closed by JMPerez** 2017-08-31 22:17 UTC
